MIPS: Add missing include
Following error has been generated due to missing include:
art/runtime/arch/mips/entrypoints_init_mips.cc:288:27: error:
    use of undeclared identifier 'systrace_lock_logging'

This fixes aosp_mips-eng build.

Test: successful aosp_mips-eng build
Change-Id: I19920cbb7dd3d928352be95a06d5138d3d505bd0